### ISSUE TITLE
Python SDK Import Failure

### ISSUE THREAD

**Issue by JupitorGeorge** [scrapfly/python-scrapfly#13]
Just started with the first python program example and the program fails on this initial line.

"from scrapfly import ScrapeConfig, ScrapflyClient, ScrapeApiResponse"

ImportError: cannot import name 'ScrapeConfig' from partially initialized module 'scrapfly' (most likely due to a circular import)

**Comment by Granitosaurus** [comment]
Is your python script named as `scrapfly.py`? This is a common Python footgun as Python imports current directory modules so you need to rename your script to not conflict with your imports: `scrapfly.py -> myscrapfly.py`

Closing this. Let me know if this still persists after the rename though.

**Comment by JupitorGeorge** [comment]
Yes it was and thank you for the quick response!   It is working now!  Now to see if we can capture network request and responses as we do with selenium wire.
