### ISSUE TITLE
Latest Version Release?

### ISSUE THREAD

**Issue by Ge0rg3** [scrapfly/python-scrapfly#16]
Hi @jjsaunier,

Thanks for your recent commit that removes the excess print statements.

If possible please can you release this version on pypi soon? Our team is waiting on it.

Thanks

**Comment by jjsaunier** [comment]
Hello @Ge0rg3 o/

 a new version has been tagged: https://github.com/scrapfly/python-scrapfly/releases/tag/0.8.16

**Comment by Ge0rg3** [comment]
Thank you! Do you have any release notes for this?
