### ISSUE TITLE
302 Redirects and Browser Automation in js_scenario

### ISSUE THREAD

**Issue by JishuLiu6** [scrapfly/python-scrapfly#21]
Dear Scrapfly Support Team,

302 Redirect Handling:When my requests encounter a 302 redirect, the redirected request method remains 'POST'. However, the standard behavior should switch the method to 'GET'. I would like to know if there is a way to configure Scrapfly to handle 302 redirects by changing the method to 'GET'. Additionally, could you please inform me if there is an option to add allow_redirect functionality to control this behavior?
js_scenario Browser Automation:I am utilizing js_scenario for browser automation to perform actions such as clicking and inputting data. Unfortunately, these actions do not appear to be effective. I am concerned that this might be due to Cloudflare's protection, possibly identifying my requests as non-HTML content. Could you provide guidance on how to ensure that my browser automation actions are executed correctly and how to handle potential Cloudflare interruptions?
I would greatly appreciate your expertise and any recommendations you can provide to resolve these issues. Your assistance will be invaluable in helping me continue my work efficiently.
 
Thank you very much for your support.
 
Best regards

**Comment by jjsaunier** [comment]
Hello,

Thank you for reaching out.

For issues related to the 302 redirect handling and js_scenario browser automation, please refer to our dedicated support section here: [Scrapfly Support](https://scrapfly.io/docs/support). Our GitHub repository does not provide support for these services.

Best regards,
