### ISSUE TITLE
Issue using extraction_model

### ISSUE THREAD

**Issue by dataenthusiast-io** [scrapfly/python-scrapfly#24]
I was playing around with the Web Scraping API Player and successfully executed a scraping using the "real_estate_property" extraction model using CURL in Postman.

When I turned to Python, I made sure to install the SDK and storing my properly. I've tried both:

`pip install 'scrapfly-sdk'`
as well as
`pip install 'scrapfly-sdk[all]'`

However, when trying to execute the auto-generated code:

```
from scrapfly import ScrapflyClient, ScrapeConfig, ScrapeApiResponse

scrapfly = ScrapflyClient(key="SCRAPFLY_API_KEY")
result: ScrapeApiResponse = scrapfly.scrape(ScrapeConfig(
    tags=[
    "player","project:default"
    ],
    extraction_model="real_estate_property",
    cache=True,
    asp=True,
    render_js=True,
    url="https://httpbin.dev/anything"
))
```
I'm getting the error that the kwargs for 'extraction_model' is not supported:

`TypeError: ScrapeConfig.__init__() got an unexpected keyword argument 'extraction_model'`

When removing the argument, scraping works but without the expected extraction of course.

**Comment by mazen-r** [comment]
Hey @dataenthusiast-io, the SDK has new features and supported APIs, but these haven't been officially announced yet nor deployed. So, currently, you can use the repo code directly without installing it from Pypi, or you can replace the package code in your virtual environment with the repo code.
