### ISSUE TITLE
disable brotli

### ISSUE THREAD

**Issue by louisabraham** [scrapfly/python-scrapfly#4]
Hi, it seems that brotli is making our application use much more CPU. Could we have a parameter to disable brotli, even if it is installed?

**Comment by jjsaunier** [comment]
Hello, 

Yes, I will add an option to explicitly disable brotli compression even if the package is available

**Comment by jjsaunier** [comment]
@louisabraham please upgrade to the latest version `pip install scrapfly-sdk -U` you can now explicitly disable brotli even if lib is present as following : 

```python
scrapfly = ScrapflyClient(key='xxxx', brotli=False)
```

**Comment by louisabraham** [comment]
Thanks!
